api_platform:
    title: 'API FACTURANDO ECUADOR'

    # The description of the API.
    description: 'Por medio de esta plataforma podrá almarcenar sus facturas, para luego enviarlas y validarlas por el sri del Ecuador'
    version: 0.0.0
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
        versions: [3]

    formats:
        jsonld:
            mime_types: ['application/ld+json']

        json:
            mime_types: ['application/json']

        html:
            mime_types: ['text/html']

        # ...

    # The list of enabled error formats. The first one will be the default.
    error_formats:
        jsonproblem:
            mime_types: ['application/problem+json']

        jsonld:
            mime_types: ['application/ld+json']
